# Generated by Django 4.2.7 on 2025-08-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', 'Yakunlangan'), ('returned', 'Qaytarilgan')], default='completed', max_length=10),
        ),
    ]
